bachya/regenmaschine

regenmaschine/zone.py
Possibly others.  I'd guess this probably isn't required for more recent hardware but I don't imagine including the json payload would cause any issues if it isn't needed.
=> Support zone stop command on Gen-1 devices

.travis.yml, README.rst, regenmaschine/__version__.py, setup.py, tox.ini
Make 3.5 (not 3.6) the minimum Python version.
=> Use 3.5 (not 3.6) as the minimum Python version

Makefile, README.md, tox.ini
This PR moves the type-checking command into the Makefile (for consistency).
N/A
**Checklist:**
=> Moved typing command to Makefile

README.md, example.py, regenmaschine/api.py, regenmaschine/client.py, tests/const.py, tests/fixtures/__init__.py, tests/fixtures/api.py, tests/test_api.py, tests/test_client.py, tests/test_diagnostics.py, tests/test_program.py, tests/test_provision.py, tests/test_restrictions.py, tests/test_stats.py, tests/test_watering.py, tests/test_zone.py
This PR adds three new attributes to the `Client` object:
- `api_version`
- `hardware_version`
- `software_version`
N/A
**Checklist:**
=> Add API, hardware, and software version properties to client

Makefile, README.md, example.py, regenmaschine/watering.py, tests/fixtures/watering.py, tests/test_watering.py
This PR adds support for the `watering/pauseall` endpoint.
Fixes https://github.com/bachya/regenmaschine/issues/26
**Checklist:**
=> Add support for watering/pauseall

README.md, regenmaschine/program.py, tests/fixtures/program.py, tests/test_program.py
This PR adds the ability to ignore inactive programs in `programs.all()` (similar to the existing functionality in `zones.all()`).
N/A
**Checklist:**
=> Add ability to remove inactive programs from programs.all()

regenmaschine/client.py
Following up to https://github.com/bachya/regenmaschine/pull/35, this PR alters `regenmaschine.Client.from_local`'s API to exactly mimic `regenmaschine.Client.login`'s (which will make eventual, full deprecation easier).
Addresses part of #34.
**Checklist:**
=> Copy API argument optionality to Client.from_local

pylintrc, regenmaschine/api.py, regenmaschine/client.py, regenmaschine/controller.py
This PR adds the concept of a `controller` object, which is separate from the `client` (the `client` can contain many `controllers`). This helps to pave the way for remote access.
No breaking changes to original API thus far...
Addresses part of #34.
**Checklist:**
=> Add concept of Controller

example.py, regenmaschine/__init__.py, regenmaschine/client.py, regenmaschine/controller.py, regenmaschine/errors.py, tests/const.py, tests/fixtures/__init__.py, tests/test_api.py, tests/test_client.py, tests/test_diagnostics.py, tests/test_parser.py, tests/test_program.py, tests/test_provision.py, tests/test_restrictions.py, tests/test_stats.py, tests/test_watering.py, tests/test_zone.py
This PR adds a `RemoteController` to manage the RainMachine API remotely.
Addresses part of #34.
**Checklist:**
=> Add remote controller

regenmaschine/client.py
[Home Assistant's RainMachine integration was throwing lots of weird exceptions](https://github.com/home-assistant/home-assistant/issues/23650). At regular intervals, we'd see logs like this:
```
2019-05-03 04:31:12 ERROR (MainThread) [homeassistant.components.rainmachine.switch] Unable to update info for zone "60e32719b6cf_zone_6": Error requesting data from 192.168.1.100: None
```
It appears that after some amount of time, the RainMachine forcibly closes the HTTP socket that `regenmaschine` uses; as a result, that request fails and it takes _another_ request to establish a new socket. This PR modifies the client so that every request as the `Connection: close` header, which will force the connection to close each time. We might miss out on some tiny speed …
=> Add "Connection: close" to all requests

regenmaschine/api.py, regenmaschine/client.py, regenmaschine/controller.py, regenmaschine/diagnostics.py, regenmaschine/errors.py, regenmaschine/parser.py, regenmaschine/program.py, regenmaschine/provision.py, regenmaschine/restriction.py, regenmaschine/stats.py, regenmaschine/watering.py, regenmaschine/zone.py
Now that we can ensure a minimum of Python 3.6, we can use Python 3.6-style type annotations for variables.
N/A
**Checklist:**
=> Add Python 3.6-style variable type annotations

regenmaschine/__init__.py, regenmaschine/client.py, tests/test_api.py, tests/test_client.py, tests/test_diagnostics.py, tests/test_parser.py, tests/test_program.py, tests/test_provision.py, tests/test_restrictions.py, tests/test_stats.py, tests/test_watering.py, tests/test_zone.py
https://github.com/bachya/regenmaschine/pull/35 deprecated the `Client.login()` coroutine in favor of `Client.load_local()` and `Client.load_remote()`. Enough time has passed, so I'm officiall removing this method.
N/A
**Checklist:**
=> Remove deprecated Client login coroutine

.pre-commit-config.yaml, tests/async_mock.py, tests/test_client.py
This PR fixes the fact that `asynctest` no longer works in Python 3.8. The PR still ensures that it can be used for Python 3.6 and 3.7.
N/A
**Checklist:**
=> Handle asynctest not working in Python 3.8

.pre-commit-config.yaml, regenmaschine/client.py, tests/test_client.py
Previously, the client would raise a `TokenExpiredError` when the token implicitly expired (based on datetime). This PR adds the same raise when the token explicitly expires.
N/A
**Checklist:**
=> Add raising of TokenExpiredError when token explicitly expires

.github/workflows/ci.yaml
`dev` CI is currently failing because it's running the `no-commit-to-branch` pre-commit hook. This PR disables that hook during CI.
N/A
**Checklist:**
=> Ensure no-commit-to-branch hook doesn't run with CI

README.md, regenmaschine/restriction.py, tests/fixtures/restrict_response.json, tests/fixtures/unrestrict_response.json, tests/test_restrictions.py
This PR adds API calls to restrict watering activities for a time and unrestrict them later. This is equivalent to the "Snooze" page in the RainMachine web GUI:
Fixes https://github.com/bachya/regenmaschine/issues/114
**Checklist:**
=> Add API to restrict/unrestrict watering activities

examples/test_api.py, regenmaschine/watering.py, tests/test_watering.py
If users attempt to call `watering.pause_all` with a duration of more than 43200 seconds (12 hours), the RainMachine will return an `HTTP 401` (a horrible choice – especially with no context in the response body – but there you have it). This PR watches for that an throws a `ValueError` appropriately.
Fixes https://github.com/bachya/regenmaschine/issues/101
**Checklist:**
=> Handle 12-hour upper limit for pausing watering

regenmaschine/client.py
This PR ensures that a failed API request exception contains the response data.
N/A
**Checklist:**
=> Return data payload when API request fails

README.md, regenmaschine/client.py, regenmaschine/controller.py, tests/test_api.py, tests/test_client.py, tests/test_diagnostics.py, tests/test_parser.py, tests/test_program.py, tests/test_provision.py, tests/test_restrictions.py, tests/test_stats.py, tests/test_watering.py, tests/test_zone.py
[Python 3.10 increased the minimum supported TLS version to 1.2](https://bugs.python.org/issue43998) (rightly so). However, I recently learned that Gen 1 controllers are still using SSLv3 (and there are no indications that this will be updated), which causes `regenmaschine` to break. This PR reinstates SSLv3 as the minimum supported version.
This is technically a breaking change because it slightly modifies the method signatures of a few methods (`use_ssl` instead of `ssl`).
N/A
**Checklist:**
=> Force inclusion of SSLv3 to support Gen 1 controllers

regenmaschine/client.py
It turns out I didn't actually test https://github.com/bachya/regenmaschine/pull/135 against Python 3.10. 🤦🏻 When I did, I found that a protocol mismatch prevented that PR from working. This PR straightens everything out.
N/A
**Checklist:**
=> Fix bug with Gen 1 controller TLS verification

regenmaschine/client.py, tests/test_client.py
Controllers can sometimes return unparseable-as-JSON responses (especially with HTTP 4xx error codes). This isn't something we can solve directly, but we can wrap them in appropriate `RequestError` objects.
N/A
**Checklist:**
=> Catch JSON errors during requests

regenmaschine/client.py, regenmaschine/errors.py, tests/fixtures/unknown_api_call_response.json, tests/test_client.py
This PR raises a new exception (`UnknownAPICallError`) when that specific response is received from the controller. This is useful for Gen1 controllers.
N/A
**Checklist:**
=> Raise new, specific exception on unknown API call

regenmaschine/client.py, tests/test_client.py
Connector errors (e.g., attempting to query the controller when it's rebooting) throw an unhandled exception.
N/A
**Checklist:**
=> Handle controller connection errors

pyproject.toml
I was getting away with installing it in a dev environment, but it's needed in the core library.
Fixes https://github.com/bachya/regenmaschine/issues/156
**Checklist:**
=> Ensure `typing_extensions` is always installed

regenmaschine/client.py
SSIA. Inspiration from @bdraco via https://github.com/gwww/elkm1/pull/69.
N/A
**Checklist:**
=> Allow connections to Gen1 controllers when using OpenSSL 3.0+

poetry.lock, pyproject.toml
We aren't actively using Safety, and we have to [pay](https://safetycli.com/resources/plans) for it to use it in CI/CD. [GitHub CodeQL](https://codeql.github.com/) effectively does the same thing.
N/A
**Checklist:**
=> Remove Safety as a dependency
