bachya/regenmaschine

regenmaschine/__init__.py, regenmaschine/client.py, tests/test_client.py, tests/test_diagnostics.py, tests/test_parser.py, tests/test_program.py, tests/test_provision.py, tests/test_restrictions.py, tests/test_stats.py, tests/test_watering.py, tests/test_zone.py
This PR does a lot of cleanup:
* Moved client authentication to a standalone method (since the refresh token idea died in #19).
* Moved several client properties to be private.
N/A
**Checklist:**
=> Initial commit

example.py, regenmaschine/client.py
This PR makes `host` a public property of the `Client` object.
N/A
**Checklist:**
=> Make host a public property of Client

tests/test_api.py, tests/test_diagnostics.py, tests/test_parser.py, tests/test_program.py, tests/test_provision.py, tests/test_restrictions.py, tests/test_stats.py, tests/test_watering.py, tests/test_zone.py
This PR breaks the previously monolithic tests into smaller, more atomic tests.
N/A
**Checklist:**
=> Split tests into bite-sized pieces

README.md, regenmaschine/program.py, tests/fixtures/program.py, tests/test_program.py
This PR adds the ability to enable and disable programs by their ID.
N/A
**Checklist:**
=> Enable disable programs

README.md, regenmaschine/program.py, regenmaschine/zone.py, tests/fixtures/zone.py, tests/test_zone.py
This PR adds the ability to enable and disable zones by ID.
N/A
**Checklist:**
=> Add ability to enable and disable zones

regenmaschine/zone.py, tests/test_zone.py
This PR fixes an incorrect URL when enabling/disabling a zone.
N/A
**Checklist:**
=> Fix a bug in enabling/disabling a zone

regenmaschine/client.py
This PR alters the under-the-hood guts of how a client (really, a local client) is created. It doesn't eliminate the existing API (`regenmaschine.login`), but does add a deprecation warning to that message.
Addresses part of https://github.com/bachya/regenmaschine/issues/34.
**Checklist:**
=> Lay foundation for new Client creation method

README.md, example.py
This PR adds an updated `README.md` and `example.py` to wrap up https://github.com/bachya/regenmaschine/issues/34.
Fixes https://github.com/bachya/regenmaschine/issues/34
**Checklist:**
=> Updated README and example.py

Pipfile
This PR attempts to clean up some too-specific version pinning in the Pipfile.
N/A
=> Cleanup Pipfile

.flake8, .github/pull_request_template.md, .github/workflows/ci.yaml, .pre-commit-config.yaml, Makefile, pyproject.toml, regenmaschine/client.py, requirements_test.txt, tests/test_api.py, tests/test_client.py, tests/test_diagnostics.py, tests/test_parser.py, tests/test_program.py, tests/test_provision.py, tests/test_restrictions.py, tests/test_stats.py, tests/test_watering.py, tests/test_zone.py
My previous CI installed way too many dependencies, was redundant, etc. This PR is an attempt to streamline it and speed it up.
N/A
**Checklist:**
=> Speed up CI

.github/workflows/ci.yaml, script/test
Now that functionality has been moved to shell scripts, we should add `shellcheck` to CI. FYI, it's currently too clunky to get it working in `pre-commit`.
N/A
**Checklist:**
=> Add shellcheck to CI

.github/release-drafter.yml
This PR adds the ability to track breaking changes via Release Drafter.
N/A
**Checklist:**
=> Add breaking changes to release drafter

.pre-commit-config.yaml, regenmaschine/client.py, regenmaschine/controller.py, regenmaschine/diagnostics.py, regenmaschine/parser.py, regenmaschine/program.py, regenmaschine/provision.py, regenmaschine/restriction.py, regenmaschine/stats.py, regenmaschine/watering.py, regenmaschine/zone.py
This PR performs some general maintenance:
* Removes unnecessary type annotations on variables
* Smarter kwargs on requests
N/A
**Checklist:**
=> General cleanup

regenmaschine/client.py, regenmaschine/controller.py
=> Fix bug with SSL cert verification

regenmaschine/program.py, tests/fixtures/program_response.json, tests/test_program.py
This PR alters the response when getting all programs to be a dict for easier lookup.
N/A
**Checklist:**
=> Alter programs payload

regenmaschine/client.py
Previously, the client would encapsulate errors in a strange way. This PR properly re-raises them. 
N/A
**Checklist:**
=> Properly re-raise errors

regenmaschine/client.py
This PR adds a `DEBUG` log statement to the client's request method. Additionally, it also makes that request method private.
N/A
**Checklist:**
=> Add debug statement to request method

regenmaschine/client.py, regenmaschine/controller.py
This PR implements [PEP 561](https://www.python.org/dev/peps/pep-0561/) and publishes the fact that this library is typed.
N/A
**Checklist:**
=> Implement PEP 561

.pre-commit-config.yaml, regenmaschine/zone.py
This PR adds the [`pyupgrade`](https://github.com/asottile/pyupgrade) pre-commit hook to help us take advantage of new Python features depending on what versions we support.
N/A
**Checklist:**
=> Add pyupgrade pre-commit hook

regenmaschine/client.py
This current exceptions swallow useful information.
Fixes https://github.com/bachya/aiowatttime/issues/<ISSUE ID>
**Checklist:**
=> Provide better exception raises in the Client

regenmaschine/program.py, regenmaschine/zone.py
This PR fixes an issue where 1st generation controllers couldn't start or stop programs and zones.
N/A
**Checklist:**
=> Fix bug with programs/zones on 1st generation controllers

README.md
Self-explanatory.
N/A
**Checklist:**
=> Add documentation note regarding RainMachine Premium Services (and remote access)

.github/workflows/ci.yaml, .pre-commit-config.yaml, README.md, pyproject.toml, regenmaschine/api.py, regenmaschine/client.py, regenmaschine/controller.py, regenmaschine/diagnostics.py, regenmaschine/parser.py, regenmaschine/program.py, regenmaschine/provision.py, regenmaschine/restriction.py, regenmaschine/stats.py, regenmaschine/watering.py, regenmaschine/zone.py
This PR makes Python 3.8 the minimum supported version.
N/A
**Checklist:**
=> Make Python 3.8 the minimum supported version

tests/fixtures/machine_get_update_response.json, tests/test_machine.py
This PR updates the test fixture that tests `controller.machine.get_firmware_update_status` with a more accurate, "from the field" data example.
N/A
**Checklist:**
=> Update firmware update test fixture

.rtx.toml
=> Add `rtx` config

regenmaschine/client.py
=> Reduce default ciphers to maintain Gen1 compatibility with OpenSSL 3.1
